/*
INSERT INTO MEDICAMENTOS VALUES ('ASP','ASPIRINA',2);
INSERT INTO MEDICAMENTOS VALUES ('PAR','PARACETAMOL',3);
INSERT INTO MEDICAMENTOS VALUES ('IBU','IBUPROFENO',4);

INSERT INTO COMPANIAS VALUES ('SS','SEGURIDAD SOCIAL');
INSERT INTO COMPANIAS VALUES ('AS','ASISA MUTUA SEGUROS');
INSERT INTO COMPANIAS VALUES ('AD','ADESLAS');

INSERT INTO TarifasComp VALUES ('ASP','SS',1.9);
INSERT INTO TarifasComp VALUES ('PAR','SS',2.8);
INSERT INTO TarifasComp VALUES ('IBU','SS',3.7);
INSERT INTO TarifasComp VALUES ('ASP','AD',1.7);
INSERT INTO TarifasComp VALUES ('PAR','AD',2.7);


INSERT INTO TICKETS VALUES (1,'01/01/2009');
INSERT INTO TICKETS VALUES (2,'03/03/2009');
INSERT INTO TICKETS VALUES (3,'17/03/2009');

INSERT INTO LINTICKETS VALUES (1,1,'ASP',2,5);
INSERT INTO LINTICKETS VALUES (1,2,'ASP',2,11);
INSERT INTO LINTICKETS VALUES (1,3,'PAR',3,6);
INSERT INTO LINTICKETS VALUES (1,4,'PAR',3,5);
INSERT INTO LINTICKETS VALUES (1,5,'PAR',3,7);
INSERT INTO LINTICKETS VALUES (1,6,'IBU',4,12);
INSERT INTO LINTICKETS VALUES (1,7,'IBU',4,8);
INSERT INTO LINTICKETS VALUES (2,1,'IBU',4,9);


INSERT INTO RECETAS VALUES (1,1,2,SYSDATE,'JUAN MOLES','01/01/1970','AD');
INSERT INTO RECETAS VALUES (2,1,4,SYSDATE,'PACO PEREZ','01/01/1970','SS');
INSERT INTO RECETAS VALUES (3,1,7,SYSDATE,'MARICARMEN','01/01/1970','SS');
INSERT INTO RECETAS VALUES (4,2,1,SYSDATE,'LUISA PEREZ','01/01/1970','SS');

